import org.antlr.v4.runtime.tree.ParseTreeVisitor;

import sun.font.TrueTypeFont;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import java.io.IOException;

public class main {
    public static void main(String[] args) throws IOException{

	// we expect exactly one argument: the name of the input file
	if (args.length!=1) {
	    System.err.println("\n");
	    System.err.println("Simple calculator\n");
	    System.err.println("=================\n\n");
	    System.err.println("Please give as input argument a filename\n");
	    System.exit(-1);
	}
	String filename=args[0];

	// open the input file
	CharStream input = CharStreams.fromFileName(filename);
	    //new ANTLRFileStream (filename); // depricated
	
	// create a lexer/scanner
	implLexer lex = new implLexer(input);
	
	// get the stream of tokens from the scanner
	CommonTokenStream tokens = new CommonTokenStream(lex);
	
	// create a parser
	implParser parser = new implParser(tokens);
	
	// and parse anything from the grammar for "start"
	ParseTree parseTree = parser.start();

	// Construct an interpreter and run it on the parse tree
	Interpreter interpreter = new Interpreter();
	interpreter.visit(parseTree);
    }
}

// We write an interpreter that implements interface
// "implVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a double.

class Interpreter extends AbstractParseTreeVisitor<Double> implements implVisitor<Double> {

    static Environment env=new Environment();
    
    public Double visitStart(implParser.StartContext ctx){
		for(implParser.CommandContext c:ctx.cs) visit(c);
		return null;
    };

    public Double visitSingleCommand(implParser.SingleCommandContext ctx){
		return visit(ctx.c);
    }

    public Double visitMultipleCommands(implParser.MultipleCommandsContext ctx){
		for(implParser.CommandContext c:ctx.cs) visit(c);
		return null;
    }
    
    public Double visitAssignment(implParser.AssignmentContext ctx){
		double v=visit(ctx.e);
		env.setVariable(ctx.x.getText(),v);
		return null;
    }
    
    public Double visitOutput(implParser.OutputContext ctx){
		double v=visit(ctx.e);
		System.out.println(v);
		return null;
    }

    public Double visitWhileLoop(implParser.WhileLoopContext ctx){
		while(visit(ctx.c).equals(1.0)) {
			visit(ctx.p);
		}

		return null;
    }
    
    public Double visitParenthesis(implParser.ParenthesisContext ctx){
		return visit(ctx.e);
    };
	
	
    public Double visitVariable(implParser.VariableContext ctx){
		return env.getVariable(ctx.x.getText());
    };
    
    public Double visitAddition(implParser.AdditionContext ctx){
		if(ctx.op.getText().equals("+")) {
			return visit(ctx.e1) + visit(ctx.e2);
		} else {
			return visit(ctx.e1) - visit(ctx.e2);
		} 
    };

    public Double visitMultiplication(implParser.MultiplicationContext ctx){
		if (ctx.op.getText().equals("*"))
			return visit(ctx.e1) * visit(ctx.e2);
		else
			return visit(ctx.e1) / visit(ctx.e2);
    };

    public Double visitConstant(implParser.ConstantContext ctx){
		return double.parsedouble(ctx.c.getText()); 
	};

	public Double visitMinus(implParser.MinusContext ctx){
		if(ctx.op.getText().equals("-"))
			return -visit(ctx.e);
		else
			return visit(ctx.e);
	};

	public Boolean visitCompareExpressions(implParser.CompareExpressionsContext ctx){
		double v1=visit(ctx.e1);
		double v2=visit(ctx.e2);
		if(ctx.op.getText().equals("!=")){
			if(!(v1.equals(v2))){
				return true;
			}else{
				return false;
			}
		} else if(ctx.op.getText().equals("==")){
			if(v1.equals(v2)){
				return true;
			}else{
				return false;
			}
		} else if(ctx.op.getText().equals(">")){
			if(v1 > v2){
				return true;
			}else{
				return false;
			}
		} else if(ctx.op.getText().equals("<")){
			if(v1 < v2){
				return true;
			}else{
				return false;
			}
		} else if(ctx.op.getText().equals(">=")){
			if(v1 >= v2){
				return true;
			}else{
				return false;
			}
		} else if(ctx.op.getText().equals("<=")){
			if(v1 <= v2){
				return true;
			}else{
				return false;
			}
		}

	};

	public Boolean visitAnd(implParser.AndContext ctx){
		boolean c1=visit(ctx.con1);
		boolean c2=visit(ctx.con2);
		if(ctx.op.getText().equals("&&")){
			if ((boolean)c1 == true && (boolean)c2 == true){
				return true;
			}else{
				return false;
			}
			if (c1 == false && c2 == false){
				return true;
			}else{
				return false;
			}
		}
	};

	public Boolean visitOr(implParser.OrContext ctx){
		boolean c1=visit(ctx.con1);
		boolean c2=visit(ctx.con2);
		if(ctx.op.getText().equals("||")){
			if (c1 == false && c2 == false){
				return false;
			} else{
				return true;
			}
		}
	};



}

